# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-03 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0023_auto_20171016_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionfiscalgeneral',
            name='eleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Eleccion'),
        ),
    ]
