# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0025_auto_20171022_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='opciones',
            field=models.ManyToManyField(related_name='elecciones', to='elecciones.Opcion'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='elecciones.Partido'),
        ),
    ]
