# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def mover_oficiales(apps, schema_editor):
    VotoMesaReportado = apps.get_model('elecciones', 'VotoMesaReportado')
    VotoMesaOficial = apps.get_model('elecciones', 'VotoMesaOficial')
    for v in VotoMesaOficial.objects.all():
        VotoMesaReportado.objects.create(votos=v.votos, mesa=v.mesa, opcion=v.opcion)
        v.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0023_auto_20171016_1648'),
        ('elecciones', '0026_auto_20171022_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votomesareportado',
            name='fiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscales.Fiscal'),
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together=set([('mesa', 'opcion', 'fiscal')]),
        ),

        migrations.RunPython(mover_oficiales),
    ]
