# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0027_auto_20171024_0019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votomesaoficial',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='votomesaoficial',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='votomesaoficial',
            name='opcion',
        ),
        migrations.DeleteModel(
            name='VotoMesaOficial',
        ),
    ]
