# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0029_auto_20190301_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='nombre_corto',
            field=models.CharField(default='', max_length=30),
        ),
    ]
