# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-02 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0030_auto_20190302_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secciondeponderacion',
            name='seccion',
        ),
    ]
