# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0031_remove_secciondeponderacion_seccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeccionDePonderacion',
            new_name='AgrupacionPK',
        ),
        migrations.AddField(
            model_name='circuito',
            name='cantidad_electores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
