# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-02 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0032_auto_20190302_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuito',
            name='cantidad_electores',
        ),
    ]
