# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-05 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0033_remove_circuito_cantidad_electores'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='carga_confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
