# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-07 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0034_mesa_carga_confirmada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuito',
            options={'ordering': ('id',), 'verbose_name': 'Circuito electoral', 'verbose_name_plural': 'Circuitos electorales'},
        ),
    ]
