# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-07 22:02
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0035_auto_20190307_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='votomesareportado',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='votomesareportado',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
