# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-09 19:43
from __future__ import unicode_literals

from django.db import migrations


def borrar_cargas_repetidas(apps, schema_editor):

    Mesa = apps.get_model('elecciones', 'Mesa')

    for mesa in Mesa.objects.filter(votomesareportado__isnull=False):
        seen = []
        for r in mesa.votomesareportado_set.order_by('fiscal'):
            if r.opcion in seen:
                print(f'carga de <{r.opcion.nombre}> repetida para mesa {mesa.numero}' )
                r.delete()
            else:
                seen.append(r.opcion)


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0036_auto_20190307_1902'),
    ]

    operations = [
        migrations.RunPython(borrar_cargas_repetidas),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            # antes solo se permitia una carga de opcion por mesa y por fiscal
            # es decir, multiples cargas de actas.
            unique_together=set([('mesa', 'opcion')]),
        ),
    ]
