# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0005_auto_20171017_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message_id',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='email',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
