# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0006_auto_20171024_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='foto_edited',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='attachments/edited', width_field='width'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='problema',
            field=models.CharField(blank=True, choices=[('acta repetida', 'acta repetida'), ('no es una foto válida', 'no es una foto válida'), ('no se entiende', 'no se entiende')], max_length=100, null=True),
        ),
    ]
