# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0008_auto_20190305_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='problema',
            field=models.CharField(blank=True, choices=[('no es una foto válida', 'no es una foto válida'), ('no se entiende', 'no se entiende')], max_length=100, null=True),
        ),
    ]
